version: '3.8'

services:
  web:
    build: .
    container_name: heptaconexiones_web
    ports:
      - "5000:5001"
    volumes:
      - .:/app
      - uploads_data:/app/uploads
      - logs_data:/app/logs
    environment:
      - GUNICORN_WORKERS=5
      - DATABASE_URL=postgresql://user:password@db:5432/heptaconexiones
    env_file:
      - .env
    depends_on:
      - db

  db:
    image: postgres:13
    container_name: heptaconexiones_db
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: heptaconexiones
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  postgres_data:
  uploads_data:
  logs_data: