version: '3.8'

services:
  web:
    build: .
    container_name: heptaconexiones_web
    ports:
      - "5000:5001"
    volumes:
      - .:/app
      - uploads_data:/app/uploads
      - logs_data:/app/logs
      # El siguiente volumen asegura que la base de datos SQLite persista
      # entre reinicios del contenedor.
      - heptaconexiones_data:/app/instance
    environment:
      - GUNICORN_WORKERS=5
    env_file:
      - .env

volumes:
  heptaconexiones_data:
  uploads_data:
  logs_data:
