"""Initial migration.

Revision ID: 4c6040e8e75d
Revises:
Create Date: 2025-09-19 18:30:31.844810

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4c6040e8e75d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('alias_perfiles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre_perfil', sa.String(), nullable=False),
    sa.Column('alias', sa.String(), nullable=False),
    sa.Column('norma', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('alias'),
    sa.UniqueConstraint('nombre_perfil')
    )
    op.create_table('configuracion',
    sa.Column('clave', sa.String(), nullable=False),
    sa.Column('valor', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('clave')
    )
    op.create_table('roles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nombre')
    )
    op.create_table('usuarios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('nombre_completo', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('password_hash', sa.String(), nullable=False),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.Column('fecha_creacion', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('auditoria_acciones',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=True),
    sa.Column('accion', sa.String(), nullable=False),
    sa.Column('tipo_objeto', sa.String(), nullable=True),
    sa.Column('objeto_id', sa.Integer(), nullable=True),
    sa.Column('detalles', sa.Text(), nullable=True),
    sa.Column('fecha', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('preferencias_notificaciones',
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('email_notif_estado', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('usuario_id')
    )
    op.create_table('proyectos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('fecha_creacion', sa.DateTime(), nullable=False),
    sa.Column('creador_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['creador_id'], ['usuarios.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nombre')
    )
    op.create_table('reportes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('creador_id', sa.Integer(), nullable=False),
    sa.Column('filtros', sa.Text(), nullable=False),
    sa.Column('programado', sa.Boolean(), nullable=False),
    sa.Column('frecuencia', sa.String(), nullable=True),
    sa.Column('destinatarios', sa.Text(), nullable=True),
    sa.Column('ultima_ejecucion', sa.DateTime(), nullable=True),
    sa.Column('fecha_creacion', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['creador_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_dashboard_preferences',
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('widgets_config', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('usuario_id')
    )
    op.create_table('usuario_roles',
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('rol_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['rol_id'], ['roles.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('usuario_id', 'rol_id')
    )
    op.create_table('conexiones',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('codigo_conexion', sa.String(), nullable=False),
    sa.Column('proyecto_id', sa.Integer(), nullable=False),
    sa.Column('tipo', sa.String(), nullable=False),
    sa.Column('subtipo', sa.String(), nullable=False),
    sa.Column('tipologia', sa.String(), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('detalles_json', sa.Text(), nullable=True),
    sa.Column('estado', sa.String(), nullable=False),
    sa.Column('solicitante_id', sa.Integer(), nullable=True),
    sa.Column('realizador_id', sa.Integer(), nullable=True),
    sa.Column('aprobador_id', sa.Integer(), nullable=True),
    sa.Column('fecha_creacion', sa.DateTime(), nullable=False),
    sa.Column('fecha_modificacion', sa.DateTime(), nullable=False),
    sa.Column('detalles_rechazo', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['aprobador_id'], ['usuarios.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['proyecto_id'], ['proyectos.id'], ),
    sa.ForeignKeyConstraint(['realizador_id'], ['usuarios.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['solicitante_id'], ['usuarios.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('codigo_conexion')
    )
    op.create_table('proyecto_usuarios',
    sa.Column('proyecto_id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['proyecto_id'], ['proyectos.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('proyecto_id', 'usuario_id')
    )
    op.create_table('archivos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('conexion_id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=True),
    sa.Column('tipo_archivo', sa.String(), nullable=False),
    sa.Column('nombre_archivo', sa.String(), nullable=False),
    sa.Column('fecha_subida', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['conexion_id'], ['conexiones.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('comentarios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('conexion_id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=True),
    sa.Column('contenido', sa.Text(), nullable=False),
    sa.Column('fecha_creacion', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['conexion_id'], ['conexiones.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('historial_estados',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('conexion_id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=True),
    sa.Column('estado', sa.String(), nullable=False),
    sa.Column('detalles', sa.Text(), nullable=True),
    sa.Column('fecha', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['conexion_id'], ['conexiones.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('notificaciones',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('mensaje', sa.Text(), nullable=False),
    sa.Column('url', sa.String(), nullable=False),
    sa.Column('conexion_id', sa.Integer(), nullable=True),
    sa.Column('leida', sa.Boolean(), nullable=False),
    sa.Column('fecha_creacion', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['conexion_id'], ['conexiones.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('notificaciones')
    op.drop_table('historial_estados')
    op.drop_table('comentarios')
    op.drop_table('archivos')
    op.drop_table('proyecto_usuarios')
    op.drop_table('conexiones')
    op.drop_table('usuario_roles')
    op.drop_table('user_dashboard_preferences')
    op.drop_table('reportes')
    op.drop_table('proyectos')
    op.drop_table('preferencias_notificaciones')
    op.drop_table('auditoria_acciones')
    op.drop_table('usuarios')
    op.drop_table('roles')
    op.drop_table('configuracion')
    op.drop_table('alias_perfiles')
    # ### end Alembic commands ###
